apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-web
  name: portfolio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-web
  template:
    metadata:
      labels:
        app: portfolio-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - image: ghcr.io/erlint1212/portfolio-website:2cc8ac8
          name: portfolio-web
          imagePullPolicy: Always
          resources: {}
          envFrom:
            - configMapRef:
                name: portfolio-web-configmap
